language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
install:
- pip install pytest
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    pip install pytest pytest-cov pep8 coveralls;
  fi
- pip install -e .
- npm install -g jshint
script:
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    py.test --cov earthreader --durations=10 &&
    pep8 ||
    exit $?;
  else
    py.test --durations=10;
  fi
- earthreader -h > /dev/null
- if [ `python -c 'import sys; print(sys.version_info[0])'` != '3' ]; then
    python -c "from earthreader.web.app import app; print(app.test_client().get('/').data)" | python tests/html5check.py -h ||
    exit $?;
  fi
- jshint earthreader/web/static/js/master.js
after_success:
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    coveralls;
  fi
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
