language: python
python:
- pypy
- 2.6
- 2.7
- 3.3
- 3.4
install:
- sudo apt-get install ack-grep
- pip install pytest 'libsass>=0.3.0'
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    pip install pytest pytest-cov pep8 coveralls;
  fi
- pip install -e .
- npm install -g jshint
script:
- python -m libearth.version
- python setup.py --version
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    py.test --cov earthreader --durations=10 &&
    pep8 ||
    exit $?;
    if [[ $(ack-grep '\t') ]]; then echo 'Do not use hardtabs'; exit 1; fi;
  else
    py.test --durations=10;
  fi
- earthreader -h > /dev/null
- python tests/html5lint.py
- jshint earthreader/web/static/js/master.js
after_success:
- if [ `python -c 'from platform import *; print(python_implementation())'` != 'PyPy' ]; then
    coveralls;
  fi
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    - "chat.freenode.net#earthreader"
    on_success: change
    on_failure: always
